# Generated by Django 4.2.27 on 2025-12-07 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notehistory',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='notes.note'),
        ),
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='notes.tag'),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['note', 'vote_type'], name='votes_note_id_389bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user', 'created_at'], name='votes_user_id_a33ac6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('note', 'user'), ('note', 'company')},
        ),
        migrations.AddIndex(
            model_name='notehistory',
            index=models.Index(fields=['note', '-changed_at'], name='note_histor_note_id_87231b_idx'),
        ),
        migrations.AddIndex(
            model_name='notehistory',
            index=models.Index(fields=['changed_at'], name='note_histor_changed_30efb1_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['workspace', 'note_type', 'is_draft'], name='notes_workspa_bfc07c_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['note_type', 'is_draft', 'created_at'], name='notes_note_ty_80fa10_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['title'], name='notes_title_333029_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-created_at'], name='notes_created_f9cdd1_idx'),
        ),
    ]
